### ISSUE TITLE
Broken example due to strl

### ISSUE THREAD

**Issue by BenWiederhake** [thosakwe/t2b#10]
Steps to reproduce:  Compile t2b and run `./build/bin/t2b example/hello.t2b | hd`

Expected behavior: Precisely one newline, i.e.:

    00000000  48 65 6c 6c 6f 2c 20 54  32 42 21 21 21 0a        |Hello, T2B!!!.|

Actual behavior: Two newlines, i.e.:

    00000000  48 65 6c 6c 6f 2c 20 54  32 42 21 21 21 0a 0a     |Hello, T2B!!!..|

What I think:
- `str` behaves correctly.  It produces no newlines.
- I can't see any problem in the code, as `std::endl` is used only in this context, and only once.

**Comment by thosakwe** [comment]
Interesting, thanks for opening the issue. Which OS are you running?

**Comment by BenWiederhake** [comment]
Debian, but shouldn't that be irrelevant?

**Comment by thosakwe** [comment]
It should be irrelevant, but I was wondering if it would turn out to be some sort Windows-specific behavior.

That being said, I'm about to take a run, but I'll be working on t2b when I get back, so this will likely be resolved before the end of the day.

**Comment by BenWiederhake** [comment]
Take your time.  Maybe I'll even send a PR if I find out what it is.  I really like that it's so short and simple.

**Comment by thosakwe** [comment]
Thanks! Appreciate that a lot. Ultimately the goal was to create a tool with "just enough" features, so it should be an easy project for me to manage.

**Comment by thosakwe** [comment]
I've found a fix. Adding an extra "if (stream.eof())" check after reading `command` seemed to do the trick; I guess that when the stream is empty, `command` is still set to `strl`, and thus emits an empty line again.

Will roll this in a sec...

**Comment by BenWiederhake** [comment]
Doesn't this introduce a new bug, namely that the last command might get ignored if it's literally the last few bytes of the input file?  That is, not even a newline after it?

And this does not fix the problem: Running `./bin/t2b ../example/interpolation.t2b` prints two newlines per "T2B!!!!!!!!!!"

**Comment by BenWiederhake** [comment]
Also, I seem to be unable to re-open this issue (?)

**Comment by BenWiederhake** [comment]
I built the wrong version, I'm stupid.  It does work now, sorry.

**Comment by thosakwe** [comment]
In response to your question, it shouldn't skip the last command.

For example, this works:

```
Tobes-MacBook-Air:example thosakwe$ echo endl | t2b | xxd
00000000: 0a                                       .
Tobes-MacBook-Air:example thosakwe$ echo strl | t2b | xxd
00000000: 0a                                       .
Tobes-MacBook-Air:example thosakwe$ echo str b strl | t2b | xxd
00000000: 620a                                     b.
```

**Comment by BenWiederhake** [comment]
Maybe you forgot that `echo` also produces a newline, meaning that the command is not exactly the last thing of the stream.  Try this:

    $ echo -n 'str "hello" endl' | ./bin/t2b | hd

In this case, the `endl` doesn't produce any output.

I found out how to do this, you'll see the PR in a moment.

**Comment by thosakwe** [comment]
Oh, good point, thank you.

**Comment by thosakwe** [comment]
I'm thinking that I could just modify `command` at the start of each iteration so that it's empty.

**Comment by thosakwe** [comment]
```cpp
  while (!stream.eof()) {
        command.clear();
        stream >> command;

        if (command.empty()) continue;
```

**Comment by BenWiederhake** [comment]
Or don't throw away the information `operator>>` gives you. :P

I'm not saying that I like the interface, I'm just saying that it *does* provide all the necessary details.
