### ISSUE TITLE
Change the "hex" command to take a parameter

### ISSUE THREAD

**Issue by blizzard4591** [thosakwe/t2b#5]
I believe that the "hex" command should be changed to accept a parameter, which can be either "ON" or "OFF", with this parameter being mandatory.

Imagine you are editing a large t2b file where hex mode is repeatedly switched on and off. Inserting a new code segment can easily and intransparently break everything after it by toggling the hex mode.

Adding this parameter improves readability and enables a developer to enforce the "correct" hex handling mode for a segment of code :)

**Comment by thosakwe** [comment]
Agreed. What about hex/binary/octal literals? #1

**Comment by pentaphobe** [comment]
Came here to say the same thing

Another option would be to have hex/octal/binary work as blocks

```
hex
  # emit 0x10
   u8 10

   # emit 0x24 
    u32 24

   # does hex affect counters as well?
    times 10
        str "16 times!!!"
    endtimes
endhex
```

**Comment by thosakwe** [comment]
Going to close this now, as the ability to write hex/bin/oct literals IMO is the better option.

See #1.

Thanks for opening this issue! Your contribution was appreciated. Hopefully the resulting solution is pleasant.
